### ISSUE TITLE
[Vote ended on 2022-02-16 at ~18:30 UTC] Expand collection inclusion checklist and clarify requirements

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#67]
## Proposal

I suggest slightly expanding collection inclusion checklist and clarify requirements. See the PR https://github.com/ansible-collections/overview/pull/196

## DO NOT READ THE BELOW: The information below is for tracking progress of the topic and does not relate to the topic's idea

Simplified version of the [workflow](https://github.com/ansible-community/community-topics/blob/main/community_topics_workflow.md)

### Preparation stage

- [x] A Committee person checks the topic's content, asks the author / other persons to provide additional information if needed (adds the `waiting` label in this case).
- [x] Adds the topic to the [Board](https://github.com/orgs/ansible-community/projects/2/views/1).

### Discussion stage

- [x] If the topic is ready to be discussed, the Committee person:

  - [x] Adds the `discussion_topic` label.
  - [x] Moves the topic to the `In Discussion` column on the [Board](https://github.com/orgs/ansible-community/projects/2/views/5).
  - [x] Opens the discussion by adding a comment asking the Community and the Committee to take part in it.
- [x] No synchronous discussion is needed (there are no blockers, complications, confusion, or impasses).

### Voting stage

- [x] Depending on the topic's complexity, 1-2 weeks after the discussion was opened, the Committee person formulates vote options based on the prior discussion and gives participants reasonable amount of time to propose changes to the options (no longer than a week). The person summarizes the options in a comment and also establishes a date when the vote begins if there are no objections about the options / vote date.
- [x] In the vote date, the vote starts with the comment of a Committee person which opens the vote and establishes a date when the vote ends ($CURRENT_DATE + no longer than 21 days; usually it should not exceed 14 days, 21 days should only be used if it is known that a lot of interested persons will likely not have time to vote in a 14 days period).
- [x] The Committee person labels the topic with the `active-vote` label and moves the topic to the `Active Vote` column on the [Board](https://github.com/orgs/ansible-community/projects/2/views/5).
- [x] The Committee person adds `[Vote ends on $YYYY-MM-DD]` to the beginning of the topic's description.

### Voting result stage

- [x] The next day after the last day of the vote, the Committee person:

  - [x] Removes the `active-vote` label.
  - [x] Add a comment that the vote ended.
  - [x] Changes the beginning of the topic's description to `[Vote ended]`.
  - [x] Counts the votes separating ones made by Community and made by Committee and creates a summary comment containing the result.
  - [x] Asks another Committee person to count the votes and provide the summary.
- [x] At least two Steering Committee members count the votes and summarize the result in comments.
- [ ] The vote's result and the final decision are announced via the [Bullhorn](https://github.com/ansible/community/issues/546).

### Implementation stage

- [ ] the PR is merged:
  - [ ] Add the `implemented` label.
- [ ] A Committee person moves the topic to the `Resolved` column on the [Board](https://github.com/orgs/ansible-community/projects/2/views/5) and closes the topic.

**Comment by Andersson007** [comment]
- The essence of the proposal is suggestion to merge https://github.com/ansible-collections/overview/pull/196.
- Please take a look and suggest any changes before **11 Feb 2022**.
- If no objections, we'll start the vote (simple with +1 / -1 as available options) on **11 Feb 2022**.

**Comment by Andersson007** [comment]
[Vote will start now and will end on February **16 at 18:30 UTC**!]
Please vote here:
+1 if you're fine with the additions introduced by the [PR](https://github.com/ansible-collections/overview/pull/196)
- 1 if you're against the additions.

If you have any suggestion on wording, vote here anyway if you're OK/not OK with their meaning.

Thank you

**Comment by Andersson007** [comment]
+1

**Comment by felixfontein** [comment]
+1

**Comment by tadeboro** [comment]
+1

**Comment by markuman** [comment]
+1

**Comment by ssbarnea** [comment]
+1 also visible on review.

**Comment by jillr** [comment]
+1 (and reviewed)

**Comment by gundalow** [comment]
+1 (and reviewed)

**Comment by briantist** [comment]
+1

**Comment by acozine** [comment]
+1

**Comment by jamescassell** [comment]
+1

**Comment by Andersson007** [comment]
Count:
SC: 11 +1, 0 -1

**Comment by Andersson007** [comment]
Thanks everyone for reviewing and voting on the issue! @jillr thanks for helping with vote count!
The [PR](https://github.com/ansible-collections/overview/pull/196) has been merged.
